version: "3"

services:
  app:
    build:
      context: node
    networks:
      - nginx-node
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-node

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - nginx-node

networks:
  nginx-node:
    driver: bridge
